packages:
  - .
  - src/renderer

catalog:
  '@electron-toolkit/eslint-config-prettier': ^3.0.0
  '@electron-toolkit/eslint-config-ts': ^3.1.0
  '@electron-toolkit/preload': ^3.0.2
  '@electron-toolkit/tsconfig': ^2.0.0
  '@electron-toolkit/utils': ^4.0.0
  '@electron/notarize': ^3.1.1
  '@eslint/compat': ^2.0.0
  '@eslint/js': ^9.39.1
  '@fontsource/major-mono-display': ^5.2.8
  '@humanspeak/svelte-virtual-list': ^0.3.6
  '@jis3r/icons': ^1.22.0
  '@lucide/svelte': ^0.561.0
  '@skeletonlabs/skeleton': ^4.8.0
  '@skeletonlabs/skeleton-svelte': ^4.7.4
  '@sveltejs/adapter-static': ^3.0.10
  '@sveltejs/kit': ^2.49.2
  '@sveltejs/vite-plugin-svelte': ^6.2.1
  '@tailwindcss/forms': ^0.5.10
  '@tailwindcss/typography': ^0.5.18
  '@tailwindcss/vite': ^4.1.18
  '@types/colorthief': ^2.6.0
  '@types/node': ^25.0.1
  '@xhayper/discord-rpc': ^1.3.0
  bonjour-service: ^1.3.0
  classnames: ^2.5.1
  colorthief: ^2.6.0
  concurrently: ^9.2.1
  dayjs: ^1.11.19
  electron: github:castlabs/electron-releases#v39.2.4+wvcus
  electron-builder: ^26.3.6
  electron-liquid-glass: ^1.1.1
  electron-serve: ^3.0.0
  electron-store: ^11.0.2
  electron-vite: ^5.0.0
  eslint: ^9.39.1
  eslint-config-prettier: ^10.1.8
  eslint-plugin-prettier: ^5.5.4
  eslint-plugin-svelte: ^3.13.1
  file-type: ^21.1.1
  flow-bin: ^0.294.0
  globals: ^16.5.0
  mpris-service: ^2.1.2
  musicbrainz-api: ^0.27.0
  prettier: ^3.7.4
  prettier-plugin-svelte: ^3.4.0
  prettier-plugin-tailwindcss: ^0.7.2
  svelte: ^5.45.10
  svelte-check: ^4.3.4
  tailwindcss: ^4.1.18
  ts-md5: ^2.0.1
  typescript: ^5.9.3
  typescript-eslint: ^8.49.0
  vite: ^7.2.7
  x11: ^2.3.0

catalogMode: prefer

onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - esbuild
  - sharp
  - '@biomejs/biome'
  - abstract-socket
  - core-js
  - electron
  - electron-vibrancy
  - esbuild
  - sharp
  - usocket
